# Generated by Django 3.1.5 on 2021-01-31 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20210131_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='popular',
            new_name='hit',
        ),
    ]
